### ISSUE TITLE
MWT and XPOSinconsistencies

### ISSUE THREAD

**Issue by qipeng** [UniversalDependencies/UD_French-Rhapsodie#1]
Hi Treebank maintainers,

While working on the Shared Task this year, we found some inconsistencies in this treebank with other UD treebanks, and in particular:

1. MWTs are expressed as "+" concatenated words in the lemma field
2. The XPOS field contains the following different values, most of which look like preprocessing errors:

```
CCOMP
DISCOURSE
DoubleAux
ETRE
_
conj:reform
de
à
```

One example can be found in sentence 642 in the training set.

Thought you'd want to know!

Best,
Peng

**Comment by bguil** [comment]
* "+" in the lemma field were removed in SUD ([940ce6c](https://github.com/surfacesyntacticud/SUD_French-Rhapsodie/commit/940ce6c7380ad0de002cd7bf945b9c42a991adb3)).
 * XPOS field contains the following different values &rarr; moved to https://github.com/surfacesyntacticud/SUD_French-Rhapsodie/issues/3

**Comment by AngledLuffa** [comment]
Just a heads up, the `ETRE` tags are still present in the Rhapsodie xpos column.

**Comment by bguil** [comment]
should be fixed now (see [here](https://universal.grew.fr/?custom=6477b98be8564))

**Comment by AngledLuffa** [comment]
Excellent, thank you!

**Comment by AngledLuffa** [comment]
Can confirm:

```
grep -v "^#" fr_rhapsodie-ud-train.conllu | grep -v "^$" | cut -f 5 | sort | uniq
_
```

etc for dev & test files
