### ISSUE TITLE
Inconsistent features on "ces"

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_French-Rhapsodie#2]
In going through the various French datasets with the same general scheme, I found that Rhapsodie has `Person=3` tags on most of the `ces` words, whereas GSD, Sequoia, and ParisStories do not.  Is this something we can unify?

I personally do not think I can provide a PR for this issue, as I am not sure which standard would be better and I believe the data is transformed from SUD regardless.

Thanks!

**Comment by bguil** [comment]
The 4 SUD-native French Corpora (GSD, Sequoia, Rhapsodie and ParisStories) have now a more consistent annotation of this form (and other PRON and DET). The four corresponding UD treebanks are also updated.

**Comment by AngledLuffa** [comment]
TYVM!
